"""Trading signal model.

This module defines the Signal model which represents trading signals
generated by strategies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class SignalType(str, Enum):
    """Trading signal type.

    Types:
        BUY: Open a long position
        SELL: Open a short position
        CLOSE: Close an existing position
    """

    BUY = "BUY"
    SELL = "SELL"
    CLOSE = "CLOSE"

    def is_entry(self) -> bool:
        """Check if this is an entry signal (BUY or SELL)."""
        return self in (SignalType.BUY, SignalType.SELL)

    def is_exit(self) -> bool:
        """Check if this is an exit signal (CLOSE)."""
        return self == SignalType.CLOSE


@dataclass
class Signal:
    """Trading signal from a strategy.

    Represents a trading decision made by a strategy that should be
    executed as an order.

    Attributes:
        signal_type: Type of signal (BUY/SELL/CLOSE)
        symbol: Trading symbol (e.g., "XAUUSD")
        strategy_name: Name of the strategy that generated the signal
        timestamp: Time the signal was generated
        metadata: Additional signal context (optional)
    """

    signal_type: SignalType
    symbol: str
    strategy_name: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Optional[dict[str, Any]] = None

    def __post_init__(self) -> None:
        """Validate signal data after initialization."""
        if not self.symbol:
            raise ValueError("symbol must not be empty")
        if not isinstance(self.signal_type, SignalType):
            raise ValueError("signal_type must be a SignalType enum")

    @property
    def is_buy(self) -> bool:
        """Check if this is a BUY signal."""
        return self.signal_type == SignalType.BUY

    @property
    def is_sell(self) -> bool:
        """Check if this is a SELL signal."""
        return self.signal_type == SignalType.SELL

    @property
    def is_close(self) -> bool:
        """Check if this is a CLOSE signal."""
        return self.signal_type == SignalType.CLOSE

    def __repr__(self) -> str:
        """String representation of signal."""
        return (
            f"Signal({self.signal_type.value}, "
            f"symbol={self.symbol}, "
            f"strategy={self.strategy_name})"
        )
