"""Story 15.9 — regime ablation harness on a real ``BacktestRunner``.

Ports ``test_router_ablation_csv.py`` (story 12.9) off the never-wired
``RegimeAwareRouter`` onto the production ``RegimeActor`` path (stories
15.5-15.8). Where the old test injected pre-computed ``RegimeFeatures``
through a scripted extractor and counted *dispatches* on a mock inner
router, this test feeds **OHLCV bar fixtures through the real
``FeatureExtractor``** on a real Nautilus ``BacktestEngine`` and counts the
strategy's *orders* — the only observable that proves the 15.7 entry gate
filters trades end to end.

Ablation matrix (allow-lists pinned test-locally in ``_TEST_ALLOW_LISTS``
— Track 2.1 archived ``bollinger_mean_reversion`` with ``regimes=[]``, but
it remains the ideal RANGING gate *vehicle* here because the fixtures were
tuned to its band-touch entries; the pin restores its historical allow-list
for gate-mechanics testing without depending on roster policy):

    donchian_breakout      -> {TRENDING_UP, TRENDING_DOWN}
    bollinger_mean_reversion -> {RANGING}   (pinned; archived in roster)

    fixture            allowed strategy           blocked strategy
    -----------------  -------------------------  ------------------------
    trending_up        donchian (enters)          bollinger (0 orders)
    trending_down      donchian (enters)          bollinger (0 orders)
    ranging            bollinger (enters)         donchian  (0 orders)
    high_volatility    -- kill-switch: both 0 --

"Has teeth" = the blocked strategy submits **zero** orders. Where the
blocked strategy *would* trade with the gate off (``ranging`` -> donchian,
``high_volatility`` -> both), the ON==0 / OFF>0 contrast proves the zero
comes from the regime gate, not from a mere absence of entry signal.

R2 (design ``regime-actor-design.md`` §risk R2 — warmup delta, MEDIUM)
========================================================================
The legacy router suppressed *dispatch*: a bar classified into a regime a
strategy did not allow (or any bar during warmup) never reached that
strategy's ``on_bar`` at all. The actor model is different and this test
pins the difference:

* The ``RegimeActor`` and the strategy both subscribe to the bar stream
  independently, so the strategy's ``on_bar`` **runs for every bar**,
  including the warmup window and blocked-regime bars. Its indicators
  advance; only the *entry seam* (``BaseStrategy._regime_admits``) is gated.
* During warmup the shared ``RegimeStateStore`` has no confirmed snapshot
  (``current() is None``) so ``_regime_admits`` returns ``False`` and entries
  are suppressed — but exits are never gated (R-A).

Net effect: entries the gate-off run would have opened during the warmup /
unconfirmed window are suppressed, so ``orders_on <= orders_off`` for an
allowed strategy. That non-negative gap **is** the warmup delta. It is
strictly more conservative than the router (fewer entries, never more), so
it is FTMO-safe — see ``test_warmup_delta_is_conservative``.

Fixtures are regenerated by ``fixtures/_generate_fixtures.py``; each carries
an inline recipe header. UNKNOWN is not exercised: the rule-based
classifier never emits it post-warmup for these streams, and the
``None``-snapshot suppression path is unit-tested in
``tests/unit/strategies/test_base_strategy_regime_gate.py``.
"""

from __future__ import annotations

import csv
import importlib
from collections import Counter
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

import pytest
from nautilus_trader.model.currencies import USD
from nautilus_trader.model.data import Bar, BarType
from nautilus_trader.model.enums import AccountType, OmsType
from nautilus_trader.model.instruments import Instrument
from nautilus_trader.model.objects import Money, Price, Quantity

import src.kernel.strategies.bollinger_mean_reversion as _bollinger_module
import src.kernel.strategies.donchian_breakout as _donchian_module
from src.lab.engine import BacktestRunner, BacktestRunnerConfig
from src.lab.runner_facade import (
    _bar_type_for,
    _build_instrument,
    _build_strategy,
)
from src.config.firm_profile import (
    InstrumentRegimeConfig,
    RegimeConfig,
    RegimeThresholds,
)
from src.kernel.regime.builders import build_extractor
from src.kernel.regime.classifier import RuleBasedRegimeClassifier
from src.kernel.regime.hysteresis import HysteresisFilter
from src.kernel.regime.state_store import RegimeStateStore
from src.kernel.regime.states import RegimeState
from src.kernel.strategies.registry import StrategyRegistry

pytestmark = pytest.mark.integration

FIXTURES = Path(__file__).parent / "fixtures"
BAR_TYPE_SUFFIX = "5-MINUTE-LAST-EXTERNAL"
# Every fixture is generated at this exact length (fixtures/_generate_fixtures.py);
# a short read means a truncated / partially-parsed CSV.
EXPECTED_BARS = 280

DONCHIAN = "donchian_breakout"
BOLLINGER = "bollinger_mean_reversion"

# Test-local allow-lists (see module docstring). Donchian mirrors its live
# declaration; bollinger pins the pre-Track-2 {RANGING} list because its
# live declaration is now the archived "never route" empty set.
_TEST_ALLOW_LISTS: dict[str, frozenset[RegimeState]] = {
    DONCHIAN: frozenset({RegimeState.TRENDING_UP, RegimeState.TRENDING_DOWN}),
    BOLLINGER: frozenset({RegimeState.RANGING}),
}


@pytest.fixture(autouse=True)
def _ensure_strategies_registered():
    """Re-fire the ``@register_strategy`` decorators (mirror 12.9 fixture).

    Other unit suites call ``StrategyRegistry.clear()`` without repopulating;
    a cached module import will not re-run the decorator on a cleared
    registry. Unregister (idempotent) then reload so the regime allow-lists
    match production wiring regardless of suite ordering.
    """
    StrategyRegistry.unregister(DONCHIAN)
    StrategyRegistry.unregister(BOLLINGER)
    importlib.reload(_donchian_module)
    importlib.reload(_bollinger_module)
    # Drift guard: the ACTIVE strategy's pinned allow-list must still
    # match its live declaration — if the decorator ever changes, this
    # fails loudly instead of the matrix silently testing stale regimes.
    # (BOLLINGER is exempt: archived with regimes=[], pin is deliberate.)
    assert StrategyRegistry.get_regimes(DONCHIAN) == _TEST_ALLOW_LISTS[DONCHIAN]
    yield


# ---------------------------------------------------------------------------
# Config + fixture loading
# ---------------------------------------------------------------------------


def _thresholds() -> RegimeThresholds:
    return RegimeThresholds(
        adx_trend_min=25.0,
        adx_strong_trend=40.0,
        bb_width_low_pct=0.30,
        bb_width_high_pct=0.80,
        realized_vol_high=0.025,
        ema_slope_trend_threshold=0.0005,
    )


def _regime_config() -> RegimeConfig:
    """Enabled XAUUSD regime block matching the fixture-tuning thresholds."""
    instrument = InstrumentRegimeConfig(
        timeframe="M5",
        thresholds=_thresholds(),
        adx_period=14,
        bb_period=20,
        bb_stddev=2.0,
        bb_baseline_window=200,
        realized_vol_window=20,
        ema_slope_period=20,
        ema_slope_lookback=5,
    )
    return RegimeConfig(
        enabled=True,
        confirmation_bars=2,
        warmup_bars=50,
        feature_window=200,
        instruments={"XAUUSD": instrument},
    )


def _load_bars(fixture_name: str, bar_type: BarType) -> list[Bar]:
    """Read an OHLCV fixture CSV into Nautilus ``Bar`` objects.

    Prices/volumes are stored as their exact serialised strings so
    ``Price.from_str`` round-trips them without precision drift — the bars
    the real ``FeatureExtractor`` sees are byte-identical to the ones the
    generator classified when the recipe was tuned.
    """
    path = FIXTURES / f"{fixture_name}.csv"
    bars: list[Bar] = []
    with path.open(encoding="utf-8") as f:
        non_comment = (line for line in f if not line.lstrip().startswith("#"))
        for row in csv.DictReader(non_comment):
            ts = int(row["ts_init"])
            bars.append(
                Bar(
                    bar_type=bar_type,
                    open=Price.from_str(row["open"]),
                    high=Price.from_str(row["high"]),
                    low=Price.from_str(row["low"]),
                    close=Price.from_str(row["close"]),
                    volume=Quantity.from_str(row["volume"]),
                    ts_event=ts,
                    ts_init=ts,
                )
            )
    assert len(bars) == EXPECTED_BARS, (
        f"fixture {fixture_name}.csv parsed {len(bars)} bars, expected "
        f"{EXPECTED_BARS} — truncated CSV or a stray '#'-prefixed header row"
    )
    return bars


# ---------------------------------------------------------------------------
# Harness — one real backtest, return the strategy's order count
# ---------------------------------------------------------------------------


def _run_order_count(
    *,
    strategy_name: str,
    bars: list[Bar],
    bar_type: BarType,
    instrument: Instrument,
    regime_on: bool,
) -> int:
    """Run one real backtest and return the number of orders the strategy made.

    Mirrors ``runner_facade.run_backtest``'s regime wiring (attach the actor
    BEFORE the strategy, inject the SAME ``RegimeStateStore`` + the declared
    allow-list as runtime attributes) but drives custom fixture bars via
    ``add_data`` — the same direct-``BacktestRunner`` composition story 15.4
    used for the ordering spike. A blocked strategy never reaches its entry
    seam, so it submits zero orders (no entry => no bracket legs).
    """
    runner = BacktestRunner(
        config=BacktestRunnerConfig(
            strategy_name=strategy_name,
            initial_balance=Decimal("100000"),
            currency="USD",
        )
    )
    try:
        runner.add_venue(
            venue=instrument.id.venue,
            oms_type=OmsType.NETTING,
            account_type=AccountType.MARGIN,
            starting_balances=[Money(100_000, USD)],
            base_currency=USD,
        )
        runner.add_instrument(instrument)
        runner.add_data(bars)

        store: RegimeStateStore | None = None
        if regime_on:
            store = RegimeStateStore()
            runner.attach_regime(
                regime_config=_regime_config(),
                bar_type=bar_type,
                regime_state=store,
            )

        strategy = _build_strategy(
            strategy_name=strategy_name,
            instrument=instrument,
            bar_type=bar_type,
            params={},
        )
        if store is not None:
            strategy._regime_state = store
            strategy._allowed_regimes = _TEST_ALLOW_LISTS[strategy_name]
        runner.add_strategy(strategy)

        runner.run()
        return len(runner.engine.cache.orders())
    finally:
        runner.dispose()


@pytest.fixture(scope="module")
def _instrument_and_bar_type() -> tuple[Instrument, BarType]:
    instrument, _ = _build_instrument("XAUUSD")
    bar_type = _bar_type_for(instrument, BAR_TYPE_SUFFIX)
    return instrument, bar_type


# ---------------------------------------------------------------------------
# Ablation matrix — story 15.9
# ---------------------------------------------------------------------------


# ``blocked_trades_with_gate_off`` marks the rows where the blocked strategy
# WOULD trade with the gate off, so its ON==0 is a true ablation "teeth"
# result. For the two trending rows it is False: a mean-reversion strategy
# produces no entry signal on a clean trend regardless of the gate, so
# bollinger's zero there is a *consistency* check, not a teeth proof. The
# teeth are proven by the ranging row (below) and ``high_volatility``; that
# bollinger is gated (not merely signal-less) on the trend streams is
# established separately by ``test_fixture_confirmed_regime_matches_intent``,
# which pins each fixture's confirmed regime to its intended value.
@pytest.mark.parametrize(
    "fixture_name, allowed, blocked, blocked_trades_with_gate_off",
    [
        ("trending_up", DONCHIAN, BOLLINGER, False),
        ("trending_down", DONCHIAN, BOLLINGER, False),
        ("ranging", BOLLINGER, DONCHIAN, True),
    ],
)
def test_regime_gate_routes_to_allowed_only(
    fixture_name: str,
    allowed: str,
    blocked: str,
    blocked_trades_with_gate_off: bool,
    _instrument_and_bar_type: tuple[Instrument, BarType],
) -> None:
    """Allowed strategy enters; the blocked strategy submits zero orders."""
    instrument, bar_type = _instrument_and_bar_type
    bars = _load_bars(fixture_name, bar_type)

    allowed_on = _run_order_count(
        strategy_name=allowed,
        bars=bars,
        bar_type=bar_type,
        instrument=instrument,
        regime_on=True,
    )
    blocked_on = _run_order_count(
        strategy_name=blocked,
        bars=bars,
        bar_type=bar_type,
        instrument=instrument,
        regime_on=True,
    )

    assert allowed_on > 0, (
        f"{allowed} should enter on a {fixture_name} stream whose confirmed "
        f"regime is in its allow-list; got {allowed_on} orders"
    )
    assert blocked_on == 0, (
        f"{blocked} should submit zero orders when {fixture_name}'s regime is "
        f"outside its allow-list (the ablation gate has no teeth otherwise); "
        f"got {blocked_on}"
    )

    if blocked_trades_with_gate_off:
        blocked_off = _run_order_count(
            strategy_name=blocked,
            bars=bars,
            bar_type=bar_type,
            instrument=instrument,
            regime_on=False,
        )
        assert blocked_off > 0, (
            f"{blocked} should trade on {fixture_name} with the regime gate "
            f"OFF — otherwise the ON==0 result is mere absence of signal, not "
            f"proof the gate suppressed entries; got {blocked_off}"
        )


def test_high_volatility_kills_every_strategy(
    _instrument_and_bar_type: tuple[Instrument, BarType],
) -> None:
    """HIGH_VOLATILITY is the global kill-switch — every strategy gets zero
    orders regardless of its allow-list, while each one trades with the gate
    off (so the zero is the kill-switch, not a dead market).
    """
    instrument, bar_type = _instrument_and_bar_type
    bars = _load_bars("high_volatility", bar_type)

    for name in (DONCHIAN, BOLLINGER):
        on = _run_order_count(
            strategy_name=name,
            bars=bars,
            bar_type=bar_type,
            instrument=instrument,
            regime_on=True,
        )
        off = _run_order_count(
            strategy_name=name,
            bars=bars,
            bar_type=bar_type,
            instrument=instrument,
            regime_on=False,
        )
        assert on == 0, (
            f"{name} must submit zero orders under HIGH_VOLATILITY "
            f"(global kill-switch); got {on}"
        )
        assert off > 0, (
            f"{name} should trade on the high-volatility stream with the gate "
            f"off — proves ON==0 is the kill-switch, not a dead market; "
            f"got {off}"
        )


def test_warmup_delta_is_conservative(
    _instrument_and_bar_type: tuple[Instrument, BarType],
) -> None:
    """R2: the actor model never opens *more* entries than the gate-off run.

    The strategy's ``on_bar`` runs through warmup in the actor model, but its
    entry seam is suppressed until the regime store holds a confirmed snapshot
    (and during any unconfirmed/blocked bar). So an allowed strategy can only
    place entries the gate-off run also placed minus those falling in the
    warmup/unconfirmed window: ``0 < orders_on <= orders_off``. The gap is the
    warmup delta — strictly conservative (fewer trades, never more), hence
    FTMO-safe.
    """
    instrument, bar_type = _instrument_and_bar_type
    bars = _load_bars("trending_up", bar_type)

    orders_on = _run_order_count(
        strategy_name=DONCHIAN,
        bars=bars,
        bar_type=bar_type,
        instrument=instrument,
        regime_on=True,
    )
    orders_off = _run_order_count(
        strategy_name=DONCHIAN,
        bars=bars,
        bar_type=bar_type,
        instrument=instrument,
        regime_on=False,
    )

    assert orders_on > 0, "allowed strategy should still trade with regime ON"
    assert orders_on <= orders_off, (
        "the actor-model warmup gate must never open MORE entries than the "
        f"gate-off run (R2 warmup delta is non-negative); on={orders_on} "
        f"off={orders_off}"
    )


# ---------------------------------------------------------------------------
# Fixture integrity — pin each stream's confirmed regime to its intent
# ---------------------------------------------------------------------------


def _confirmed_tail_states(bars: list[Bar], bar_type: BarType) -> list[RegimeState]:
    """Replay the bars through the real actor pipeline; return confirmed states.

    Mirrors ``RegimeActor.on_bar`` exactly — same ``build_extractor`` wiring,
    the same ``RuleBasedRegimeClassifier`` + ``HysteresisFilter`` the factory
    builds — so this is what the shared ``RegimeStateStore`` would hold each
    bar. Only post-warmup bars (those that emit features) are returned.
    """
    cfg = _regime_config()
    instrument_cfg = cfg.instruments["XAUUSD"]
    extractor = build_extractor(str(bar_type), instrument_cfg, cfg.warmup_bars)
    classifier = RuleBasedRegimeClassifier(_thresholds())
    hysteresis = HysteresisFilter(
        bar_type=str(bar_type),
        confirmation_bars=cfg.confirmation_bars,
        thresholds=_thresholds(),
    )
    states: list[RegimeState] = []
    for bar in bars:
        features = extractor.update(bar)
        if features is None:
            continue
        ts = datetime.fromtimestamp(bar.ts_event / 1e9, tz=UTC)
        raw = classifier.decide(features)
        states.append(hysteresis.apply(raw, ts, features).current_state)
    return states


# Per fixture: the regime the allowed strategy needs to see, plus the regimes
# that MUST NOT appear in the confirmed tail because they would open the
# *blocked* strategy's gate and make its zero-order result a false negative.
#   donchian allows {TRENDING_UP, TRENDING_DOWN}; bollinger allows {RANGING}.
_TAIL = 80
_FIXTURE_REGIME_INTENT = {
    "trending_up": (
        RegimeState.TRENDING_UP,
        {RegimeState.RANGING},  # would open bollinger (the blocked strategy)
    ),
    "trending_down": (
        RegimeState.TRENDING_DOWN,
        {RegimeState.RANGING},  # would open bollinger
    ),
    "ranging": (
        RegimeState.RANGING,
        {RegimeState.TRENDING_UP, RegimeState.TRENDING_DOWN},  # would open donchian
    ),
    "high_volatility": (
        RegimeState.HIGH_VOLATILITY,
        # ANY tradable regime would open one of the two gates the kill-switch
        # is supposed to override.
        {RegimeState.TRENDING_UP, RegimeState.TRENDING_DOWN, RegimeState.RANGING},
    ),
}


@pytest.mark.parametrize("fixture_name", list(_FIXTURE_REGIME_INTENT))
def test_fixture_confirmed_regime_matches_intent(
    fixture_name: str,
    _instrument_and_bar_type: tuple[Instrument, BarType],
) -> None:
    """Each fixture's confirmed-tail regime is its intended one, and contains
    no regime that would open the blocked strategy's gate.

    This decouples the ablation assertions from the strategies' own signal
    logic: it proves the zero-order results above come from the regime the
    gate sees (e.g. bollinger is gated on a genuinely TRENDING tail, not merely
    signal-less), and it is the tripwire that fails loudly if a threshold change
    or a fixture regeneration drifts a stream out of its target regime.
    """
    _, bar_type = _instrument_and_bar_type
    bars = _load_bars(fixture_name, bar_type)
    intended, forbidden = _FIXTURE_REGIME_INTENT[fixture_name]

    tail = _confirmed_tail_states(bars, bar_type)[-_TAIL:]
    assert tail, f"{fixture_name}: no post-warmup bars to classify"

    counts = Counter(tail)
    assert counts[intended] > 0, (
        f"{fixture_name}: confirmed tail never reaches the intended "
        f"{intended.value}; distribution={ {s.value: n for s, n in counts.items()} }"
    )
    leaked = forbidden & set(tail)
    assert not leaked, (
        f"{fixture_name}: confirmed tail leaks {[s.value for s in leaked]}, "
        f"which would open the blocked strategy's gate and void the ablation; "
        f"distribution={ {s.value: n for s, n in counts.items()} }"
    )
